# Generated by Django 5.0.4 on 2024-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_alter_comment_author_alter_comment_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
