# Generated by Django 5.0.4 on 2024-05-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0010_alter_comment_thread_alter_thread_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
