# Generated by Django 5.0.4 on 2024-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0005_alter_product_status_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('0', 'On Cart'), ('1', 'To Pay'), ('2', 'To Ship'), ('3', 'To Receive'), ('4', 'Delivered')], max_length=10),
        ),
    ]
