# Generated by Django 5.0.4 on 2024-05-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0006_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "status"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["status"]},
        ),
    ]
