# Generated by Django 5.0.2 on 2024-05-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_commission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='open', max_length=12),
        ),
    ]
