# Generated by Django 5.0.2 on 2024-05-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_commission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('1_open', 'Open'), ('2_full', 'Full'), ('3_completed', 'Completed'), ('4_discontinued', 'Discontinued')], default='open', max_length=14),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('manpower', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('1_open', 'Open'), ('2_full', 'Full')], default='1_open', max_length=6)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='commissions.commission')),
            ],
            options={
                'ordering': ['status', '-manpower', 'role'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
