# Generated by Django 5.0.2 on 2024-05-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_alter_job_options_commission_author_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [models.Case(models.When(status='Open', then=models.Value(0)), models.When(status='Full', then=models.Value(1))), '-manpower', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': [models.Case(models.When(status='Pending', then=models.Value(0)), models.When(status='Accepted', then=models.Value(1)), models.When(status='Rejected', then=models.Value(2))), '-applied_on']},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='author',
            field=models.CharField(default='You', max_length=63),
        ),
    ]
